# Kubernetes Service Manifest
# Description: Exposes the model service as a LoadBalancer.

apiVersion: v1
kind: Service
metadata:
  name: mlops-model-service
spec:
  selector:
    app: mlops-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer